Migrate to Provisioning API nested root
RedHatInsights/image-builder-frontend pull request #1306
Opened 2023-08-10 15:06 UTC by ezr-ondrej

2023-08-15 14:50 UTC, ezr-ondrej commented on src/store/helpers.ts
>  export const extractProvisioningList = (
This is still keeping the backwards compatibility, but we can just wait with merging this a bit (few prod pushes) and then drop the backwards compatibility completely.

2023-09-11 09:06 UTC, lavocatt commented
Hey @ezr-ondrej, this PR now conflicts with main, can you give it a rebase on your local copy please ?

2023-09-11 09:35 UTC, lavocatt requested changes
Hey @ezr-ondrej, this PR now conflicts with main, can you give it a rebase on your local copy please ?

2023-09-11 12:16 UTC, ezr-ondrej commented on src/store/helpers.ts
>  export const extractProvisioningList = (
It's been a while and everything seems to work fine, dropping the backwards compatibility :)

2023-09-11 12:24 UTC, ezr-ondrej commented
> Hey @ezr-ondrej, this PR now conflicts with main, can you give it a rebase on your local copy please ?

Done and also dropped the backwards compatibility as it's already stable for a while in all environments :)

2023-09-11 13:18 UTC, lavocatt approved these changes
LGTM!

2023-09-11 13:19 UTC, merged