API: Move notification dispatch to Image Builder API slice
RedHatInsights/image-builder-frontend pull request #1380
Opened 2023-10-10 12:11 UTC by lucasgarfield

This commit moves the notification dispatching for creating composes and
clones into a more sensible location – the Image Builder API slice.

It is more sensible because it separates the logic of the React
component (the wizard or share images modal) from the logic of handling
the request life cycle (which is now handled entirely in the slice).

There is a subtle but significant change – a new request will be
dispatched for every request. This is the correct way to do things as it
is possible that some requests succeed, and that others fail. Insights
causes the notifications to stack on top of each other neatly, so there
is no UI problem.

To facilitate this, we also need to use use Promise.allSettled instead
of Promise.all.

2023-10-10 12:14 UTC, lucasgarfield commented
Behold!
![bearmetal](https://github.com/RedHatInsights/image-builder-frontend/assets/95542540/97a4b9b3-6b7a-4599-a075-a300b637faf5)

2023-10-11 08:24 UTC, lavocatt commented
Looks like this PR depends on https://github.com/RedHatInsights/image-builder-frontend/pull/1379 (writing it so we don't merge this one before the other)

2023-10-11 08:26 UTC, lavocatt approved these changes
This really makes a lot of sense! Very good idea :rocket:

2023-10-11 13:32 UTC, jrusz commented
/retest

2023-10-11 13:40 UTC, lavocatt requested changes
Falsely requesting changes so we don't merge this one accidentally before #1379

2023-10-12 11:17 UTC, lucasgarfield commented
/retest

2023-10-12 13:52 UTC, lavocatt approved these changes
#1379 got merged, let's have this one in too!

2023-10-12 16:14 UTC, jrusz commented
/retest

2023-10-13 07:16 UTC, regexowl approved these changes
LGTM!

2023-10-13 09:44 UTC, lucasgarfield commented
Discussed this PR with @jrusz, IQE test failure not related to this PR, the important bits all pass. Merging.

2023-10-13 09:44 UTC, merged