add ssl_certification explenation to the readme file
RedHatInsights/image-builder-frontend pull request #1436
Opened 2023-11-14 11:05 UTC by mgold1234

2023-11-16 11:28 UTC, croissanne requested changes
These seem to be mac specific instructions. Maybe we should put all mac-specific instructions in a separate section/under a separate header?

Also can you fix up the commit message a little:

```
README.md: add mac OS mock service worker instructions
```

2023-11-16 11:28 UTC, croissanne commented on README.md
> +if you want to develop in environment that automatically generated data, run the command `npm run stage-beta:msw`.
Is the data generated on the fly or mocked?

Also if it's generated
> environment _with_ generated data

2023-11-16 12:34 UTC, croissanne requested changes

2023-11-16 12:34 UTC, croissanne commented on README.md
> +
stray newline

2023-11-16 12:34 UTC, croissanne commented on README.md
> +if you want to develop in environment that automatically generated data, run the command npm run stage-beta:msw. To enable msw, you must configure SSL certification on your computer.
```suggestion
### Using MSW data
If you want to develop in environment with automatically generated data, run the command `npm run stage-beta:msw`. To enable msw, you must configure SSL certification on your computer.
```

2023-11-16 12:34 UTC, croissanne commented on README.md
> +if you want to develop in environment that automatically generated data, run the command npm run stage-beta:msw.
```suggestion
### Using MSW data
If you want to develop in environment with automatically generated data, run the command `npm run stage-beta:msw`.
```

2023-11-16 12:34 UTC, croissanne commented on README.md
> +Close the localhost screen.
Can we make this a numbered list?

```
1. Open the 'Keychain Access' application.
2. ...
```

2023-11-17 08:33 UTC, regexowl commented on README.md
> +Run npm run stage-beta:msw and open the Firefox browser to verify that it is working as expected.
```suggestion
Run `npm run stage-beta:msw` and open the Firefox browser to verify that it is working as expected.
```

2023-11-17 08:37 UTC, regexowl commented on README.md
> +Drag the certification file (usually located at /image-builder-project/image-builder-frontend/node_modules/.cache/webpack-dev-server/server.pem) to the certification list.
The path can start with the frontend folder.

```suggestion
Drag the certification file (usually located at /image-builder-frontend/node_modules/.cache/webpack-dev-server/server.pem) to the certification list.
```

2023-11-17 08:44 UTC, regexowl commented
Can you also please fix up a couple of typos in the commit message?

```
this commit adds an explanation to the readme file about how to add ssl certification to your computer (if you work on MAC) to be able to run `npm run stage-beta:msw`
```

2023-11-21 07:39 UTC, regexowl approved these changes
Looks good to me, thank you!

2023-11-21 09:39 UTC, croissanne approved these changes

2023-11-21 09:42 UTC, merged