HMS 3030 - Add iqe trigger integration
RedHatInsights/image-builder-frontend pull request #1466
Opened 2023-11-28 13:21 UTC by tkoscieln

This commit adds a iqe trigger integration.
Copied from this [file](https://github.com/osbuild/image-builder/blob/main/templates/iqe-trigger-integration.yml).

2023-11-28 15:18 UTC, jrusz approved these changes

2023-11-28 15:23 UTC, jrusz requested changes
Let's actually wait for a related app-interface MR to get merged first. We want to add promotion publish channels for the frontend and adding them first and merging this afterwards would create those channels and add a success message.

2023-11-30 11:36 UTC, tkoscieln commented
@lucasgarfield  The app-interface [MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/89415) with promotion publis channels got merged, so this is not blocked anymore by it.

2023-11-30 13:34 UTC, jrusz approved these changes

2023-11-30 13:37 UTC, merged