Wizard: Update Review step
RedHatInsights/image-builder-frontend pull request #850
Opened 2022-11-02 10:20 UTC by regexowl

Fixes #774. This matches the Review step with the updated mocks as per SPUR.

2022-11-04 10:44 UTC, regexowl commented
Additional information for an activation key is in a separate issue #822 as it should be used both in Registration and Review step.

2022-11-07 13:13 UTC, croissanne requested changes
LGTM overall, but could you edit the commit message to detail the exact changes (just a little bullet-point list or something), and maybe include a screenshot in the PR description?

2022-11-07 13:13 UTC, croissanne commented on src/Components/CreateImageWizard/CreateImageWizard.scss
> +}
Nitpick: 1 trailing newline

2022-11-07 15:00 UTC, regexowl commented on src/Components/CreateImageWizard/CreateImageWizard.scss
> +}
Fixed!

2022-11-07 15:36 UTC, croissanne approved these changes
perfect, thank you!

2022-11-07 15:36 UTC, merged