fix(HMSPROV-377) - disable image's launch button when image is not ready
RedHatInsights/image-builder-frontend pull request #880
Opened 2022-12-01 17:20 UTC by amirfefer

before: 
![Screen Shot 2022-12-01 at 18 44 46](https://user-images.githubusercontent.com/11807069/205118235-f320872a-3796-4b43-b19f-faba10100f8b.png)

after:
![Screen Shot 2022-12-01 at 18 42 51](https://user-images.githubusercontent.com/11807069/205118142-fdfcb1f1-0055-4351-b40e-04c271caf624.png)

2022-12-05 10:22 UTC, croissanne requested changes
One comment, otherwise lgtm.

Currently we don't disable the button, we just omit it in case it's not ready. Let's just omit it in case of failure as well.

2022-12-05 10:22 UTC, croissanne commented on src/Components/ImagesTable/ImageLink.js
> +          isDisabled={image.status !== 'success'}
Can we move this to/solve this in ImageLink directly? It currently returns null if there's no uploadstatus, but might as well solve it for all cases, and require that the uploadstatus is defined and has succeeded.

2022-12-05 14:48 UTC, lucasgarfield commented on src/Components/ImagesTable/ImageLink.js
> +    const provisionedImage = image.isClone ? parent : image;
This is a super nit-pick but now that we don't re-assign `image` can we make it a `const` (on line 11)?

2023-02-07 16:38 UTC, ezr-ondrej commented
Implementing in #954 it was a one liner :)

2023-02-09 08:34 UTC, ezr-ondrej commented
#954 is in, so I guess we can close this one @lucasgarfield ? :)

2023-02-09 08:41 UTC, closed without merging