Enable provisioning wizard in Ephemeral environment
RedHatInsights/image-builder-frontend pull request #897
Opened 2023-01-03 10:53 UTC by ezr-ondrej

2023-01-04 09:43 UTC, croissanne commented
/retest

2023-01-04 14:55 UTC, lucasgarfield commented
Hi Ondrej, I'm still trying to get my head around the useScalprum() and useChrome() hooks. Just for my own knowledge, would you mind explaining a bit about why these changes are needed for the ephemeral environment? How did you know that you needed to make these changes?

2023-01-05 11:28 UTC, lucasgarfield requested changes

2023-01-05 11:28 UTC, lucasgarfield commented on src/Components/ImagesTable/ImageLink.js
> +  const { initiated: chromeInitiated, isBeta, getEnvironment } = useChrome();
I think `initiated` is a typo, shouldn't it be `initialized`? 

Doesn't work for me with `initiated` but does work with `initialized`...

2023-01-12 11:02 UTC, akhil-jha commented
@ezr-ondrej can you update it please? :) I am not able to open the wizard through "Launch" yet. :)

2023-01-12 14:51 UTC, lucasgarfield commented
Superseded by #926.

2023-01-12 14:51 UTC, closed without merging